### ISSUE TITLE
Add/Save to Database

### ISSUE THREAD

**Issue by Thapa33** [mjhouse/cs499_srdesign#22]
## Description
From the manager class. How do we link to the database of the doctor , patient and Appointment. We save to the list of doctor, patient and appointment. How to populate to the database. #21

**Comment by mjhouse** [comment]
I've got a local version of the codebase that creates the database and tables if it doesn't exist at runtime. I'm working on the other instance of this issue right now (#21)- The manager will handle saving the current collection of appointments/doctors/patients to the database, so populating the database isn't an issue..
